import Foundation

class FilterGuide {
    let filters: [FilterObject] =
        [FilterObject(category: "Blur", designation: "None", name: "None"),
         FilterObject(category: "Blur", designation: "CIBoxBlur", name: "Box Blur"),
         FilterObject(category: "Blur", designation: "CIDiscBlur", name: "Disk Blur"),
         FilterObject(category: "Blur", designation: "CIGaussianBlur", name: "Gaussian Blur"),
         FilterObject(category: "Blur", designation: "CIMaskedVariableBlur", name: "Masked Variable Blur"),
         FilterObject(category: "Blur", designation: "CIMedianFilter", name: "Median Filter"),
         FilterObject(category: "Blur", designation: "CIMotionBlur", name: "Motion Blur"),
         FilterObject(category: "Blur", designation: "CINoiseReduction", name: "Noise Reduction"),
         FilterObject(category: "Blur", designation: "CIZoomBlur", name: "Zoom Blur"),
         FilterObject(category: "Color Adjustment", designation: "None", name: "None"),
         FilterObject(category: "Color Adjustment", designation: "CIColorClamp", name: "Color Clamp"),
         FilterObject(category: "Color Adjustment", designation: "CIColorControls", name: "Color Controls"),
         FilterObject(category: "Color Adjustment", designation: "CIColorMatrix", name: "Color Matrix"),
         FilterObject(category: "Color Adjustment", designation: "CIColorPolynomial", name: "Color Polynomial"),
         FilterObject(category: "Color Adjustment", designation: "CIExposureAdjust", name: "Exposure Adjust"),
         FilterObject(category: "Color Adjustment", designation: "CIGammaAdjust", name: "Gamma Adjust"),
         FilterObject(category: "Color Adjustment", designation: "CIHueAdjust", name: "Hue Adjust"),
         FilterObject(category: "Color Adjustment", designation: "CILinearToSRGBToneCurve", name: "Linear To SRGB Tone Curve"),
         FilterObject(category: "Color Adjustment", designation: "CISRGBToneCurveToLinear", name: "SRGB Tone Curve To Linear"),
         FilterObject(category: "Color Adjustment", designation: "CITemperatureAndTint", name: "Temperature And Tint"),
         FilterObject(category: "Color Adjustment", designation: "CIToneCurve", name: "Tone Curve"),
         FilterObject(category: "Color Adjustment", designation: "CIVibrance", name: "Vibrance"),
         FilterObject(category: "Color Adjustment", designation: "CIWhitePointAdjust", name: "White Point Adjust"),
         FilterObject(category: "Color Effect", designation: "None", name: "None"),
         FilterObject(category: "Color Effect", designation: "CIColorCrossPolynomial", name: "Color Cross Polynomial"),
         FilterObject(category: "Color Effect", designation: "CIColorCube", name: "Color Cube"),
         FilterObject(category: "Color Effect", designation: "CIColorCubeWithColorSpace", name: "Color Cube With Color Space"),
         FilterObject(category: "Color Effect", designation: "CIColorInvert", name: "Color Invert"),
         FilterObject(category: "Color Effect", designation: "CIColorMap", name: "Color Map"),
         FilterObject(category: "Color Effect", designation: "CIColorMonochrome", name: "Color Monochrome"),
         FilterObject(category: "Color Effect", designation: "CIColorPosterize", name: "Color Posterize"),
         FilterObject(category: "Color Effect", designation: "CIFalseColor", name: "False Color"),
         FilterObject(category: "Color Effect", designation: "CIMaskToAlpha", name: "Mask To Alpha"),
         FilterObject(category: "Color Effect", designation: "CIMaximumComponent", name: "Maximum Component"),
         FilterObject(category: "Color Effect", designation: "CIMinimumComponent", name: "Minimum Component"),
         FilterObject(category: "Color Effect", designation: "CIPhotoEffectChrome", name: "Photo Effect Chrome"),
         FilterObject(category: "Color Effect", designation: "CIPhotoEffectFade", name: "Photo Effect Fade"),
         FilterObject(category: "Color Effect", designation: "CIPhotoEffectInstant", name: "Photo Effect Instant"),
         FilterObject(category: "Color Effect", designation: "CIPhotoEffectMono", name: "Photo Effect Mono"),
         FilterObject(category: "Color Effect", designation: "CIPhotoEffectNoir", name: "Photo Effect Noir"),
         FilterObject(category: "Color Effect", designation: "CIPhotoEffectProcess", name: "Photo Effect Process"),
         FilterObject(category: "Color Effect", designation: "CIPhotoEffectTonal", name: "Photo Effect Tonal"),
         FilterObject(category: "Color Effect", designation: "CIPhotoEffectTransfer", name: "Photo Effect Transfer"),
         FilterObject(category: "Color Effect", designation: "CISepiaTone", name: "Sepia Tone"),
         FilterObject(category: "Color Effect", designation: "CIVignette", name: "Vignette"),
         FilterObject(category: "Color Effect", designation: "CIVignetteEffect", name: "Vignette Effect"),
         FilterObject(category: "Distortion Effect", designation: "None", name: "None"),
         FilterObject(category: "Distortion Effect", designation: "CIBumpDistortion", name: "Bump Distortion"),
         FilterObject(category: "Distortion Effect", designation: "CIBumpDistortionLinear", name: "Bump Distortion Linear"),
         FilterObject(category: "Distortion Effect", designation: "CICircleSplashDistortion", name: "Circle Splash Distortion"),
         FilterObject(category: "Distortion Effect", designation: "CICircularWrap", name: "Circular Wrap"),
         FilterObject(category: "Distortion Effect", designation: "CIDroste", name: "Droste"),
         FilterObject(category: "Distortion Effect", designation: "CIDisplacementDistortion", name: "Displacement Distortion"),
         FilterObject(category: "Distortion Effect", designation: "CIGlassDistortion", name: "Glass Distortion"),
         FilterObject(category: "Distortion Effect", designation: "CIGlassLozenge", name: "Glass Lozenge"),
         FilterObject(category: "Distortion Effect", designation: "CIHoleDistortion", name: "Hole Distortion"),
         FilterObject(category: "Distortion Effect", designation: "CILightTunnel", name: "Light Tunnel"),
         FilterObject(category: "Distortion Effect", designation: "CIPinchDistortion", name: "Pinch Distortion"),
         FilterObject(category: "Distortion Effect", designation: "CIStretchCrop", name: "Stretch Crop"),
         FilterObject(category: "Distortion Effect", designation: "CITorusLensDistortion", name: "Torus Lens Distortion"),
         FilterObject(category: "Distortion Effect", designation: "CITwirlDistortion", name: "Twirl Distortion"),
         FilterObject(category: "Distortion Effect", designation: "CIVortexDistortion", name: "Vortex Distortion"),
         FilterObject(category: "Generator", designation: "None", name: "None"),
         FilterObject(category: "Generator", designation: "CIStarShineGenerator", name: "Star Shine Generator"),
         FilterObject(category: "Generator", designation: "CIStripesGenerator", name: "Stripes Generator"),
         FilterObject(category: "Generator", designation: "CISunbeamsGenerator", name: "Sunbeams Generator"),
         FilterObject(category: "Gradient", designation: "None", name: "None"),
         FilterObject(category: "Gradient", designation: "CIGaussianGradient", name: "CIGaussianGradient"),
         FilterObject(category: "Gradient", designation: "CILinearGradient", name: "Linear Gradient"),
         FilterObject(category: "Gradient", designation: "CIRadialGradient", name: "Radial Gradient"),
         FilterObject(category: "Gradient", designation: "CISmoothLinearGradient", name: "Smooth Linear Gradient"),
         FilterObject(category: "Halftone Effect", designation: "None", name: "None"),
         FilterObject(category: "Halftone Effect", designation: "CICircularScreen", name: "Circular Screen"),
         FilterObject(category: "Halftone Effect", designation: "CICMYKHalftone", name: "CMYK Halftone"),
         FilterObject(category: "Halftone Effect", designation: "CIDotScreen", name: "Dot Screen"),
         FilterObject(category: "Halftone Effect", designation: "CIHatchedScreen", name: "Hatched Screen"),
         FilterObject(category: "Halftone Effect", designation: "CILineScreen", name: "Line Screen"),
         FilterObject(category: "Sharpen", designation: "None", name: "None"),
         FilterObject(category: "Sharpen", designation: "CISharpenLuminance", name: "Sharpen Luminance"),
         FilterObject(category: "Sharpen", designation: "CIUnsharpMask", name: "Unsharp Mask"),
         FilterObject(category: "Stylize", designation: "None", name: "None"),
         FilterObject(category: "Stylize", designation: "CIBloom", name: "Bloom"),
         FilterObject(category: "Stylize", designation: "CIComicEffect", name: "Comic Effect"),
         FilterObject(category: "Stylize", designation: "CIConvolution3X3", name: "Convolution 3X3"),
         FilterObject(category: "Stylize", designation: "CIConvolution5X5", name: "Convolution 5X5"),
         FilterObject(category: "Stylize", designation: "CIConvolution7X7", name: "Convolution 7X7"),
         FilterObject(category: "Stylize", designation: "CIConvolution9Horizontal", name: "Convolution 9 Horizontal"),
         FilterObject(category: "Stylize", designation: "CIConvolution9Vertical", name: "Convolution 9 Vertical"),
         FilterObject(category: "Stylize", designation: "CICrystallize", name: "Crystallize"),
         FilterObject(category: "Stylize", designation: "CIDepthOfField", name: "DepthOfField"),
         FilterObject(category: "Stylize", designation: "CIEdges", name: "Edges"),
         FilterObject(category: "Stylize", designation: "CIEdgeWork", name: "Edge Work"),
         FilterObject(category: "Stylize", designation: "CIGloom", name: "Gloom"),
         FilterObject(category: "Stylize", designation: "CIHeightFieldFromMask", name: "Height Field From Mask"),
         FilterObject(category: "Stylize", designation: "CIHexagonalPixellate", name: "Hexagonal Pixellate"),
         FilterObject(category: "Stylize", designation: "CIHighlightShadowAdjust", name: "Highlight Shadow Adjust"),
         FilterObject(category: "Stylize", designation: "CILineOverlay", name: "Line Overlay"),
         FilterObject(category: "Stylize", designation: "CIPixellate", name: "Pixellate"),
         FilterObject(category: "Stylize", designation: "CIPointillize", name: "Pointillize"),
         FilterObject(category: "Stylize", designation: "CISpotColor", name: "Spot Color"),
         FilterObject(category: "Stylize", designation: "CISpotLight", name: "Spot Light"),
         FilterObject(category: "Tile Effect", designation: "None", name: "None"),
         FilterObject(category: "Tile Effect", designation: "CIEightfoldReflectedTile", name: "Eightfold Reflected Tile"),
         FilterObject(category: "Tile Effect", designation: "CIFourfoldReflectedTile", name: "Fourfold Reflected Tile"),
         FilterObject(category: "Tile Effect", designation: "CIFourfoldRotatedTile", name: "Fourfold Rotated Tile"),
         FilterObject(category: "Tile Effect", designation: "CIFourfoldTranslatedTile", name: "Fourfold Translated Tile"),
         FilterObject(category: "Tile Effect", designation: "CIGlideReflectedTile", name: "Glide Reflected Tile"),
         FilterObject(category: "Tile Effect", designation: "CIKaleidoscope", name: "Kaleidoscope"),
         FilterObject(category: "Tile Effect", designation: "CIOpTile", name: "Op Tile"),
         FilterObject(category: "Tile Effect", designation: "CIParallelogramTile", name: "Parallelogram Tile"),
         FilterObject(category: "Tile Effect", designation: "CIPerspectiveTile", name: "Perspective Tile"),
         FilterObject(category: "Tile Effect", designation: "CISixfoldReflectedTile", name: "Sixfold Reflected Tile"),
         FilterObject(category: "Tile Effect", designation: "CISixfoldRotatedTile", name: "Sixfold Rotated Tile"),
         FilterObject(category: "Tile Effect", designation: "CITriangleKaleidoscope", name: "Triangle Kaleidoscope"),
         FilterObject(category: "Tile Effect", designation: "CITriangleTile", name: "Triangle Tile"),
         FilterObject(category: "Tile Effect", designation: "CITwelvefoldReflectedTile", name: "Twelvefold Reflected Tile")
    ]
}
